packages:
  - packages/**
  - playgrounds/**
catalog:
  '@antfu/eslint-config': ^3.11.2
  '@antfu/ni': ^0.23.1
  '@antfu/utils': ^0.7.10
  '@exampledev/new.css': ^1.1.3
  '@iconify-json/bxl': ^1.2.1
  '@iconify-json/carbon': ^1.2.4
  '@iconify-json/logos': ^1.2.3
  '@iconify-json/ri': ^1.2.3
  '@iconify-json/simple-icons': ^1.2.13
  '@iconify-json/tabler': ^1.2.8
  '@nuxt/content': ^2.13.4
  '@nuxt/eslint': ^0.7.2
  '@nuxt/kit': ^3.14.1592
  '@nuxt/module-builder': ^0.8.3
  '@nuxt/schema': ^3.14.1592
  '@nuxt/test-utils': ^3.14.4
  '@opentelemetry/api': ^1.9.0
  '@parcel/watcher': ^2.5.0
  '@pinia/nuxt': ^0.8.0
  '@types/diff': ^6.0.0
  '@types/markdown-it': ^14.1.2
  '@types/markdown-it-link-attributes': ^3.0.5
  '@types/node': ^22.10.1
  '@types/prompts': ^2.4.9
  '@types/ua-parser-js': ^0.7.39
  '@types/which': ^3.0.4
  '@types/ws': ^8.5.13
  '@unocss/core': ^0.64.1
  '@unocss/eslint-config': ^0.64.1
  '@unocss/nuxt': ^0.64.1
  '@unocss/preset-attributify': ^0.64.1
  '@unocss/preset-icons': ^0.64.1
  '@unocss/preset-mini': ^0.64.1
  '@unocss/preset-uno': ^0.64.1
  '@unocss/reset': ^0.64.1
  '@unocss/runtime': ^0.64.1
  '@vitest/ui': ^2.1.6
  '@vue/devtools-applet': 7.6.4
  '@vue/devtools-core': 7.6.4
  '@vue/devtools-kit': 7.6.4
  '@vueuse/core': ^12.0.0
  '@vueuse/integrations': ^12.0.0
  '@vueuse/nuxt': ^12.0.0
  '@xterm/addon-fit': ^0.10.0
  '@xterm/xterm': ^5.5.0
  birpc: ^0.2.19
  bumpp: ^9.8.1
  consola: ^3.2.3
  conventional-changelog-cli: ^5.0.0
  cronstrue: ^2.52.0
  cypress: ^13.16.0
  defu: ^6.1.4
  destr: ^2.0.3
  diff: ^7.0.0
  error-stack-parser-es: ^0.1.5
  eslint: ^9.15.0
  eslint-flat-config-utils: ^0.4.0
  eslint-plugin-antfu: ^2.7.0
  eslint-plugin-format: ^0.1.2
  esno: ^4.8.0
  execa: ^7.2.0
  fast-npm-meta: ^0.2.2
  flatted: ^3.3.2
  floating-vue: 5.2.2
  focus-trap: ^7.6.2
  fuse.js: ^7.0.0
  get-port-please: ^3.1.2
  global-directory: ^4.0.1
  hookable: ^5.5.3
  image-meta: ^0.2.1
  is-installed-globally: ^1.0.0
  json-editor-vue: ^0.16.0
  launch-editor: ^2.9.1
  lint-staged: ^15.2.10
  local-pkg: ^0.5.1
  magicast: ^0.3.5
  markdown-it: ^14.1.0
  markdown-it-link-attributes: ^4.0.1
  nanoid: ^5.0.9
  nitropack: ^2.10.4
  nuxt: ^3.14.1592
  nuxt-eslint-auto-explicit-import: ^0.1.1
  nypm: ^0.4.1
  ofetch: ^1.4.1
  ohash: ^1.1.4
  pathe: ^1.1.2
  perfect-debounce: ^1.0.0
  pinia: ^2.2.8
  pkg-types: ^1.2.1
  prompts: ^2.4.2
  quicktype-core: ^23.0.170
  rc9: ^2.1.2
  scule: ^1.3.0
  semver: ^7.6.3
  shiki: ^1.24.0
  simple-git: ^3.27.0
  simple-git-hooks: ^2.11.1
  sirv: ^3.0.0
  splitpanes: ^3.1.5
  taze: ^0.18.0
  theme-vitesse: ^0.8.3
  tinyglobby: ^0.2.10
  typescript: 5.6.3
  ua-parser-js: ^1.0.39
  unbuild: ^2.0.0
  unimport: ^3.14.1
  unocss: ^0.64.1
  unplugin-vue-markdown: ^0.26.3
  v-lazy-show: ^0.2.4
  vanilla-jsoneditor: ^0.23.8
  vis-data: ^7.1.9
  vis-network: ^9.1.9
  vite: ^6.0.1
  vite-hot-client: ^0.2.4
  vite-plugin-inspect: ^0.10.3
  vite-plugin-vue-inspector: 5.1.3
  vitest: ^2.1.6
  vue: ^3.5.13
  vue-router: ^4.5.0
  vue-tsc: ^2.1.10
  vue-virtual-scroller: 2.0.0-beta.8
  which: ^3.0.1
  ws: ^8.18.0
