ignoreWorkspaceRootCheck: true
strictPeerDependencies: false
autoInstallPeers: true
resolutionMode: highest
shamefullyHoist: true
shellEmulator: true
trustPolicy: no-downgrade

packages:
  - packages/**
  - playgrounds/**

catalogs:
  buildtools:
    '@discoveryjs/cli': ^2.14.7
    '@discoveryjs/discovery': 1.0.0-beta.92
    '@nuxt/module-builder': ^1.0.2
    '@parcel/watcher': ^2.5.6
    '@pinia/nuxt': ^0.11.3
    '@unocss/core': ^66.6.0
    '@unocss/eslint-config': ^66.6.0
    '@unocss/nuxt': ^66.6.0
    '@unocss/preset-attributify': ^66.6.0
    '@unocss/preset-icons': ^66.6.0
    '@unocss/preset-mini': ^66.6.0
    '@unocss/preset-uno': ^66.6.0
    '@vitejs/devtools': ^0.0.0-alpha.23
    '@vueuse/nuxt': ^14.2.1
    chokidar: ^5.0.0
    esbuild: ^0.27.3
    exsolve: ^1.0.8
    lightningcss: ^1.31.1
    nitropack: ^2.13.1
    nuxt: ^4.3.1
    rollup: ^4.57.1
    shiki-codegen: ^3.22.0
    turbo: ^2.8.5
    unbuild: ^3.6.1
    unocss: ^66.6.0
    unplugin-vue: ^7.1.1
    unplugin-vue-markdown: ^29.2.0
    vite: ^8.0.0-beta.13
  cli:
    '@antfu/eslint-config': ^7.4.3
    '@antfu/ni': ^28.2.0
    '@nuxt/eslint': ^1.15.1
    '@nuxt/test-utils': ^4.0.0
    '@vitest/ui': ^4.0.18
    bumpp: ^10.4.1
    conventional-changelog-cli: ^5.0.0
    cypress: ^13.17.0
    eslint: ^9.39.2
    eslint-flat-config-utils: ^3.0.1
    eslint-plugin-antfu: ^3.2.1
    eslint-plugin-format: ^1.4.0
    lint-staged: ^16.2.7
    nuxt-eslint-auto-explicit-import: ^0.1.1
    simple-git-hooks: ^2.13.1
    taze: ^19.9.2
    tsx: ^4.21.0
    typescript: ^5.9.3
    vitest: ^4.0.18
    vue-tsc: ^3.2.4
  frontend:
    '@antfu/utils': ^9.3.0
    '@unocss/reset': ^66.6.0
    '@unocss/runtime': ^66.6.0
    '@vue/devtools-applet': ^8.0.6
    '@vue/devtools-core': ^8.0.6
    '@vueuse/core': ^14.2.1
    '@vueuse/integrations': ^14.2.1
    '@xterm/addon-fit': ^0.11.0
    '@xterm/xterm': ^6.0.0
    birpc: ^4.0.0
    cronstrue: ^3.12.0
    diff: ^8.0.3
    error-stack-parser-es: ^1.0.5
    floating-vue: ^5.2.2
    focus-trap: ^7.8.0
    fuse.js: ^7.1.0
    hookable: ^6.0.1
    json-editor-vue: ^0.18.1
    markdown-it: ^14.1.0
    markdown-it-link-attributes: ^4.0.1
    my-ua-parser: ^2.0.4
    ofetch: ^1.5.1
    ohash: ^2.0.11
    pathe: ^2.0.3
    perfect-debounce: ^2.1.0
    pinia: ^3.0.4
    quicktype-core: 22.0.0
    scule: ^1.3.0
    shiki: ^3.22.0
    splitpanes: ^4.0.4
    structured-clone-es: ^1.0.0
    theme-vitesse: ^1.0.0
    v-lazy-show: ^0.3.0
    vanilla-jsoneditor: ^3.11.0
    vis-data: ^8.0.3
    vis-network: ^10.0.2
    vite-hot-client: ^2.1.0
    vue: ^3.5.28
    vue-router: ^5.0.2
    vue-virtual-scroller: ^2.0.0-beta.8
  icons:
    '@iconify-json/bxl': ^1.2.2
    '@iconify-json/carbon': ^1.2.18
    '@iconify-json/logos': ^1.2.10
    '@iconify-json/ph': ^1.2.2
    '@iconify-json/ri': ^1.2.10
    '@iconify-json/simple-icons': ^1.2.70
    '@iconify-json/tabler': ^1.2.26
  playground:
    '@exampledev/new.css': ^1.1.3
  prod:
    '@nuxt/kit': ^4.3.1
    '@vue/devtools-kit': ^8.0.6
    consola: ^3.4.2
    defu: ^6.1.4
    destr: ^2.0.5
    execa: ^8.0.1
    fast-npm-meta: ^1.2.1
    get-port-please: ^3.2.0
    image-meta: ^0.2.2
    is-installed-globally: ^1.0.0
    launch-editor: ^2.12.0
    local-pkg: ^1.1.2
    magicast: ^0.5.2
    nypm: ^0.6.5
    pkg-types: ^2.3.0
    prompts: ^2.4.2
    semver: ^7.7.4
    simple-git: ^3.30.0
    sirv: ^3.0.2
    tinyglobby: ^0.2.15
    vite-plugin-inspect: ^11.3.3
    vite-plugin-vue-tracer: ^1.2.0
    which: ^5.0.0
    ws: ^8.19.0
  types:
    '@nuxt/schema': ^4.3.1
    '@types/diff': ^8.0.0
    '@types/markdown-it': ^14.1.2
    '@types/markdown-it-link-attributes': ^3.0.5
    '@types/node': ^25.2.3
    '@types/prompts': ^2.4.9
    '@types/which': ^3.0.4
    '@types/ws': ^8.18.1
    '@unhead/schema': ^2.1.4
    '@vitejs/devtools-kit': ^0.0.0-alpha.23
    unimport: ^5.6.0
onlyBuiltDependencies:
  - '@parcel/watcher'
  - better-sqlite3
  - cypress
  - esbuild
  - json-editor-vue
  - simple-git-hooks
  - unrs-resolver
  - vue-demi
