packages:
  - packages/**
  - playgrounds/**
catalog:
  '@antfu/eslint-config': ^4.10.1
  '@antfu/ni': ^24.1.0
  '@antfu/utils': ^9.1.0
  '@discoveryjs/cli': ^2.13.1
  '@discoveryjs/discovery': 1.0.0-beta.92
  '@exampledev/new.css': ^1.1.3
  '@iconify-json/bxl': ^1.2.2
  '@iconify-json/carbon': ^1.2.8
  '@iconify-json/logos': ^1.2.4
  '@iconify-json/ri': ^1.2.5
  '@iconify-json/simple-icons': ^1.2.28
  '@iconify-json/tabler': ^1.2.17
  '@nuxt/content': ^3.3.0
  '@nuxt/eslint': ^1.2.0
  '@nuxt/kit': ^3.16.0
  '@nuxt/module-builder': ^0.8.4
  '@nuxt/schema': ^3.16.0
  '@nuxt/test-utils': ^3.17.2
  '@opentelemetry/api': ^1.9.0
  '@parcel/watcher': ^2.5.1
  '@pinia/nuxt': ^0.10.1
  '@shikijs/langs-precompiled': ^3.2.1
  '@types/diff': ^7.0.1
  '@types/markdown-it': ^14.1.2
  '@types/markdown-it-link-attributes': ^3.0.5
  '@types/node': ^22.13.10
  '@types/prompts': ^2.4.9
  '@types/which': ^3.0.4
  '@types/ws': ^8.18.0
  '@unocss/core': ^66.0.0
  '@unocss/eslint-config': ^66.0.0
  '@unocss/nuxt': ^66.0.0
  '@unocss/preset-attributify': ^66.0.0
  '@unocss/preset-icons': ^66.0.0
  '@unocss/preset-mini': ^66.0.0
  '@unocss/preset-uno': ^66.0.0
  '@unocss/reset': ^66.0.0
  '@unocss/runtime': ^66.0.0
  '@vitest/ui': ^3.0.8
  '@vue/devtools-applet': ^7.7.2
  '@vue/devtools-core': ^7.7.2
  '@vue/devtools-kit': ^7.7.2
  '@vueuse/core': ^13.0.0
  '@vueuse/integrations': ^13.0.0
  '@vueuse/nuxt': ^13.0.0
  '@xterm/addon-fit': ^0.10.0
  '@xterm/xterm': ^5.5.0
  birpc: ^2.2.0
  bumpp: ^10.1.0
  consola: ^3.4.0
  conventional-changelog-cli: ^5.0.0
  cronstrue: ^2.56.0
  cypress: ^13.17.0
  defu: ^6.1.4
  destr: ^2.0.3
  diff: ^7.0.0
  error-stack-parser-es: ^1.0.5
  esbuild: ^0.25.1
  eslint: ^9.22.0
  eslint-flat-config-utils: ^2.0.1
  eslint-plugin-antfu: ^3.1.1
  eslint-plugin-format: ^1.0.1
  esno: ^4.8.0
  execa: ^9.5.2
  fast-npm-meta: ^0.3.1
  floating-vue: ^5.2.2
  focus-trap: ^7.6.4
  fuse.js: ^7.1.0
  get-port-please: ^3.1.2
  hookable: ^5.5.3
  image-meta: ^0.2.1
  is-installed-globally: ^1.0.0
  json-editor-vue: ^0.18.1
  launch-editor: ^2.10.0
  lint-staged: ^15.5.0
  local-pkg: ^1.1.1
  magicast: ^0.3.5
  markdown-it: ^14.1.0
  markdown-it-link-attributes: ^4.0.1
  my-ua-parser: ^2.0.4
  nanoid: ^5.1.3
  nitropack: ^2.11.6
  nuxt: ^3.16.0
  nuxt-eslint-auto-explicit-import: ^0.1.1
  nypm: ^0.6.0
  ofetch: ^1.4.1
  ohash: ^2.0.11
  pathe: ^2.0.3
  perfect-debounce: ^1.0.0
  pinia: ^3.0.1
  pkg-types: ^2.1.0
  prompts: ^2.4.2
  quicktype-core: 22.0.0
  scule: ^1.3.0
  semver: ^7.7.1
  shiki: ^3.2.1
  shiki-codegen: ^3.2.1
  simple-git: ^3.27.0
  simple-git-hooks: ^2.11.1
  sirv: ^3.0.1
  splitpanes: ^3.2.0
  structured-clone-es: ^1.0.0
  taze: ^19.0.2
  theme-vitesse: ^0.8.3
  tinyglobby: ^0.2.12
  typescript: ^5.8.2
  unbuild: ^3.5.0
  unimport: ^4.1.2
  unocss: ^66.0.0
  unplugin-vue-markdown: ^28.3.1
  v-lazy-show: ^0.3.0
  vanilla-jsoneditor: ^3.0.0
  vis-data: ^7.1.9
  vis-network: ^9.1.9
  vite: ^6.2.1
  vite-hot-client: ^2.0.4
  vite-plugin-inspect: ^11.0.0
  vite-plugin-vue-tracer: ^0.1.1
  vitest: ^3.0.8
  vue: ^3.5.13
  vue-router: ^4.5.0
  vue-tsc: ^2.2.8
  vue-virtual-scroller: ^2.0.0-beta.8
  which: ^5.0.0
  ws: ^8.18.1
onlyBuiltDependencies:
  - '@parcel/watcher'
  - better-sqlite3
  - cypress
  - esbuild
  - json-editor-vue
  - simple-git-hooks
  - vue-demi
