packages:
  - packages/**
  - playgrounds/**

shamefullyHoist: true
ignoreWorkspaceRootCheck: true
strictPeerDependencies: false
autoInstallPeers: true
resolutionMode: highest

catalogs:
  buildtools:
    '@discoveryjs/cli': ^2.14.7
    '@discoveryjs/discovery': 1.0.0-beta.92
    '@nuxt/module-builder': ^1.0.2
    '@parcel/watcher': ^2.5.1
    '@pinia/nuxt': ^0.11.3
    '@unocss/core': ^66.5.9
    '@unocss/eslint-config': ^66.5.9
    '@unocss/nuxt': ^66.5.9
    '@unocss/preset-attributify': ^66.5.9
    '@unocss/preset-icons': ^66.5.9
    '@unocss/preset-mini': ^66.5.9
    '@unocss/preset-uno': ^66.5.9
    '@vitejs/devtools': ^0.0.0-alpha.7
    '@vueuse/nuxt': ^14.0.0
    esbuild: ^0.25.12
    exsolve: ^1.0.8
    lightningcss: ^1.30.2
    nitropack: ^2.12.9
    nuxt: ^4.2.1
    rollup: ^4.53.3
    shiki-codegen: ^3.15.0
    unbuild: ^3.6.1
    unocss: ^66.5.9
    unplugin-vue: ^7.0.8
    unplugin-vue-markdown: ^29.2.0
    vite: ^7.2.4
  cli:
    '@antfu/eslint-config': ^6.2.0
    '@antfu/ni': ^27.0.1
    '@nuxt/eslint': ^1.10.0
    '@nuxt/test-utils': ^3.20.1
    '@vitest/ui': ^4.0.13
    bumpp: ^10.3.1
    conventional-changelog-cli: ^5.0.0
    cypress: ^13.17.0
    eslint: ^9.39.1
    eslint-flat-config-utils: ^2.1.4
    eslint-plugin-antfu: ^3.1.1
    eslint-plugin-format: ^1.0.2
    lint-staged: ^16.2.7
    nuxt-eslint-auto-explicit-import: ^0.1.1
    simple-git-hooks: ^2.13.1
    taze: ^19.9.0
    tsx: ^4.20.6
    typescript: ^5.9.3
    vitest: ^4.0.13
    vue-tsc: ^3.1.5
  frontend:
    '@antfu/utils': ^9.3.0
    '@unocss/reset': ^66.5.9
    '@unocss/runtime': ^66.5.9
    '@vue/devtools-applet': ^8.0.5
    '@vue/devtools-core': ^8.0.5
    '@vueuse/core': ^14.0.0
    '@vueuse/integrations': ^14.0.0
    '@xterm/addon-fit': ^0.10.0
    '@xterm/xterm': ^5.5.0
    birpc: ^2.8.0
    cronstrue: ^3.9.0
    diff: ^8.0.2
    error-stack-parser-es: ^1.0.5
    floating-vue: ^5.2.2
    focus-trap: ^7.6.6
    fuse.js: ^7.1.0
    hookable: ^5.5.3
    json-editor-vue: ^0.18.1
    markdown-it: ^14.1.0
    markdown-it-link-attributes: ^4.0.1
    my-ua-parser: ^2.0.4
    ofetch: ^1.5.1
    ohash: ^2.0.11
    pathe: ^2.0.3
    perfect-debounce: ^2.0.0
    pinia: ^3.0.4
    quicktype-core: 22.0.0
    scule: ^1.3.0
    shiki: ^3.15.0
    splitpanes: ^4.0.4
    structured-clone-es: ^1.0.0
    theme-vitesse: ^1.0.0
    v-lazy-show: ^0.3.0
    vanilla-jsoneditor: ^3.10.0
    vis-data: ^8.0.3
    vis-network: ^10.0.2
    vite-hot-client: ^2.1.0
    vue: ^3.5.25
    vue-router: ^4.6.3
    vue-virtual-scroller: ^2.0.0-beta.8
  icons:
    '@iconify-json/bxl': ^1.2.2
    '@iconify-json/carbon': ^1.2.14
    '@iconify-json/logos': ^1.2.10
    '@iconify-json/ph': ^1.2.2
    '@iconify-json/ri': ^1.2.6
    '@iconify-json/simple-icons': ^1.2.60
    '@iconify-json/tabler': ^1.2.23
  playground:
    '@exampledev/new.css': ^1.1.3
  prod:
    '@nuxt/kit': ^4.2.1
    '@vue/devtools-kit': ^8.0.5
    consola: ^3.4.2
    defu: ^6.1.4
    destr: ^2.0.5
    execa: ^8.0.1
    fast-npm-meta: ^0.4.7
    get-port-please: ^3.2.0
    image-meta: ^0.2.2
    is-installed-globally: ^1.0.0
    launch-editor: ^2.12.0
    local-pkg: ^1.1.2
    magicast: ^0.5.1
    nypm: ^0.6.2
    pkg-types: ^2.3.0
    prompts: ^2.4.2
    semver: ^7.7.3
    simple-git: ^3.30.0
    sirv: ^3.0.2
    tinyglobby: ^0.2.15
    vite-plugin-inspect: ^11.3.3
    vite-plugin-vue-tracer: ^1.1.3
    which: ^5.0.0
    ws: ^8.18.3
  types:
    '@nuxt/schema': ^4.2.1
    '@types/diff': ^8.0.0
    '@types/markdown-it': ^14.1.2
    '@types/markdown-it-link-attributes': ^3.0.5
    '@types/node': ^24.10.1
    '@types/prompts': ^2.4.9
    '@types/which': ^3.0.4
    '@types/ws': ^8.18.1
    '@unhead/schema': ^2.0.19
    '@vitejs/devtools-kit': ^0.0.0-alpha.7
    unimport: ^5.5.0
onlyBuiltDependencies:
  - '@parcel/watcher'
  - better-sqlite3
  - cypress
  - esbuild
  - json-editor-vue
  - simple-git-hooks
  - unrs-resolver
  - vue-demi
