ignoreWorkspaceRootCheck: true
strictPeerDependencies: false
autoInstallPeers: true
resolutionMode: highest
shamefullyHoist: true
shellEmulator: true
trustPolicy: no-downgrade

packages:
  - packages/**
  - playgrounds/**

catalogs:
  buildtools:
    '@discoveryjs/cli': ^2.14.7
    '@discoveryjs/discovery': 1.0.0-beta.92
    '@nuxt/module-builder': ^1.0.2
    '@parcel/watcher': ^2.5.6
    '@pinia/nuxt': ^0.11.3
    '@unocss/core': ^66.6.7
    '@unocss/eslint-config': ^66.6.7
    '@unocss/nuxt': ^66.6.7
    '@unocss/preset-attributify': ^66.6.7
    '@unocss/preset-icons': ^66.6.7
    '@unocss/preset-mini': ^66.6.7
    '@unocss/preset-uno': ^66.6.7
    '@vitejs/devtools': ^0.1.13
    '@vueuse/nuxt': ^14.2.1
    chokidar: ^5.0.0
    esbuild: ^0.28.0
    exsolve: ^1.0.8
    lightningcss: ^1.32.0
    nitropack: ^2.13.3
    nuxt: ^4.4.2
    rollup: ^4.60.1
    shiki-codegen: ^4.0.2
    skills-npm: ^1.1.1
    turbo: ^2.9.5
    unbuild: ^3.6.1
    unocss: ^66.6.7
    unplugin-vue: ^7.1.1
    unplugin-vue-markdown: ^30.0.0
    vite: ^8.0.7
  cli:
    '@antfu/eslint-config': ^8.0.0
    '@antfu/ni': ^30.0.0
    '@nuxt/eslint': ^1.15.2
    '@nuxt/test-utils': ^4.0.0
    '@playwright/test': ^1.49.0
    '@vitest/ui': ^4.1.3
    bumpp: ^11.0.1
    cypress: ^15.13.1
    eslint: ^10.2.0
    eslint-flat-config-utils: ^3.1.0
    eslint-plugin-antfu: ^3.2.2
    eslint-plugin-format: ^2.0.1
    lint-staged: ^16.4.0
    nuxt-eslint-auto-explicit-import: ^0.1.1
    simple-git-hooks: ^2.13.1
    taze: ^19.11.0
    tsx: ^4.21.0
    typescript: ^6.0.2
    vitest: ^4.1.3
    vue-tsc: ^3.2.6
  frontend:
    '@antfu/utils': ^9.3.0
    '@unocss/reset': ^66.6.7
    '@unocss/runtime': ^66.6.7
    '@vue/devtools-applet': ^8.1.1
    '@vue/devtools-core': ^8.1.1
    '@vueuse/core': ^14.2.1
    '@vueuse/integrations': ^14.2.1
    '@xterm/addon-fit': ^0.11.0
    '@xterm/xterm': ^6.0.0
    birpc: ^4.0.0
    cronstrue: ^3.14.0
    error-stack-parser-es: ^1.0.5
    floating-vue: ^5.2.2
    focus-trap: ^8.0.1
    fuse.js: ^7.3.0
    hookable: ^6.1.0
    json-editor-vue: ^0.18.1
    markdown-it: ^14.1.1
    markdown-it-link-attributes: ^4.0.1
    ofetch: ^1.5.1
    ohash: ^2.0.11
    pathe: ^2.0.3
    perfect-debounce: ^2.1.0
    pinia: ^3.0.4
    quicktype-core: 22.0.0
    scule: ^1.3.0
    shiki: ^4.0.2
    splitpanes: ^4.0.4
    structured-clone-es: ^2.0.0
    theme-vitesse: ^1.0.0
    ua-parser-modern: ^0.1.1
    v-lazy-show: ^0.3.0
    vanilla-jsoneditor: ^3.12.0
    vis-data: ^8.0.3
    vis-network: ^10.0.2
    vite-hot-client: ^2.1.0
    vue: ^3.5.32
    vue-router: ^5.0.4
    vue-virtual-scroller: ^2.0.1
  icons:
    '@iconify-json/bxl': ^1.2.4
    '@iconify-json/carbon': ^1.2.20
    '@iconify-json/logos': ^1.2.11
    '@iconify-json/ph': ^1.2.2
    '@iconify-json/ri': ^1.2.10
    '@iconify-json/simple-icons': ^1.2.77
    '@iconify-json/tabler': ^1.2.33
  inlined:
    package-manager-detector: ^1.6.0
  playground:
    '@exampledev/new.css': ^1.1.3
  prod:
    '@nuxt/kit': ^4.4.2
    '@vue/devtools-kit': ^8.1.1
    consola: ^3.4.2
    defu: ^6.1.7
    destr: ^2.0.5
    fast-npm-meta: ^1.4.2
    get-port-please: ^3.2.0
    image-meta: ^0.2.2
    launch-editor: ^2.13.2
    local-pkg: ^1.1.2
    magicast: ^0.5.2
    pkg-types: ^2.3.0
    semver: ^7.7.4
    sirv: ^3.0.2
    tinyexec: ^1.1.1
    tinyglobby: ^0.2.16
    unstorage: ^1.17.5
    vite-plugin-inspect: ^12.0.0-beta.1
    vite-plugin-vue-tracer: ^1.3.0
    which: ^6.0.1
    ws: ^8.20.0
  types:
    '@nuxt/schema': ^4.4.2
    '@types/markdown-it': ^14.1.2
    '@types/markdown-it-link-attributes': ^3.0.5
    '@types/node': ^25.5.2
    '@types/semver': ^7.7.1
    '@types/which': ^3.0.4
    '@types/ws': ^8.18.1
    '@unhead/schema': ^2.1.13
    '@vitejs/devtools-kit': ^0.1.13
    unimport: ^6.0.2
onlyBuiltDependencies:
  - '@parcel/watcher'
  - better-sqlite3
  - cypress
  - esbuild
  - json-editor-vue
  - simple-git-hooks
  - unrs-resolver
  - vue-demi
