packages:
  - packages/**
  - playgrounds/**
catalog:
  '@antfu/eslint-config': ^4.3.0
  '@antfu/ni': ^23.3.1
  '@antfu/utils': ^9.1.0
  '@discoveryjs/cli': ^2.13.1
  '@discoveryjs/discovery': 1.0.0-beta.92
  '@exampledev/new.css': ^1.1.3
  '@iconify-json/bxl': ^1.2.2
  '@iconify-json/carbon': ^1.2.7
  '@iconify-json/logos': ^1.2.4
  '@iconify-json/ri': ^1.2.5
  '@iconify-json/simple-icons': ^1.2.25
  '@iconify-json/tabler': ^1.2.16
  '@nuxt/content': ^2.13.4
  '@nuxt/eslint': ^1.1.0
  '@nuxt/kit': ^3.15.4
  '@nuxt/module-builder': ^0.8.4
  '@nuxt/schema': ^3.15.4
  '@nuxt/test-utils': ^3.15.4
  '@opentelemetry/api': ^1.9.0
  '@parcel/watcher': ^2.5.1
  '@pinia/nuxt': ^0.10.1
  '@shikijs/langs-precompiled': ^3.0.0
  '@types/diff': ^7.0.1
  '@types/markdown-it': ^14.1.2
  '@types/markdown-it-link-attributes': ^3.0.5
  '@types/node': ^22.13.4
  '@types/prompts': ^2.4.9
  '@types/which': ^3.0.4
  '@types/ws': ^8.5.14
  '@unocss/core': ^66.0.0
  '@unocss/eslint-config': ^66.0.0
  '@unocss/nuxt': ^66.0.0
  '@unocss/preset-attributify': ^66.0.0
  '@unocss/preset-icons': ^66.0.0
  '@unocss/preset-mini': ^66.0.0
  '@unocss/preset-uno': ^66.0.0
  '@unocss/reset': ^66.0.0
  '@unocss/runtime': ^66.0.0
  '@vitest/ui': ^3.0.5
  '@vue/devtools-applet': ^7.7.2
  '@vue/devtools-core': ^7.7.2
  '@vue/devtools-kit': ^7.7.2
  '@vueuse/core': ^12.7.0
  '@vueuse/integrations': ^12.7.0
  '@vueuse/nuxt': ^12.7.0
  '@xterm/addon-fit': ^0.10.0
  '@xterm/xterm': ^5.5.0
  birpc: ^2.2.0
  bumpp: ^10.0.3
  consola: ^3.4.0
  conventional-changelog-cli: ^5.0.0
  cronstrue: ^2.54.0
  cypress: ^13.17.0
  defu: ^6.1.4
  destr: ^2.0.3
  diff: ^7.0.0
  error-stack-parser-es: ^1.0.5
  esbuild: ^0.25.0
  eslint: ^9.20.1
  eslint-flat-config-utils: ^2.0.1
  eslint-plugin-antfu: ^3.1.0
  eslint-plugin-format: ^1.0.1
  esno: ^4.8.0
  execa: ^9.5.2
  fast-npm-meta: ^0.3.1
  floating-vue: ^5.2.2
  focus-trap: ^7.6.4
  fuse.js: ^7.1.0
  get-port-please: ^3.1.2
  hookable: ^5.5.3
  image-meta: ^0.2.1
  is-installed-globally: ^1.0.0
  json-editor-vue: ^0.17.3
  launch-editor: ^2.10.0
  lint-staged: ^15.4.3
  local-pkg: ^1.0.0
  magicast: ^0.3.5
  markdown-it: ^14.1.0
  markdown-it-link-attributes: ^4.0.1
  my-ua-parser: ^2.0.4
  nanoid: ^5.1.0
  nitropack: ^2.10.4
  nuxt: ^3.15.4
  nuxt-eslint-auto-explicit-import: ^0.1.1
  nypm: ^0.5.2
  ofetch: ^1.4.1
  ohash: ^1.1.4
  pathe: ^2.0.3
  perfect-debounce: ^1.0.0
  pinia: ^3.0.1
  pkg-types: ^2.0.0
  prompts: ^2.4.2
  quicktype-core: 22.0.0
  rc9: ^2.1.2
  scule: ^1.3.0
  semver: ^7.7.1
  shiki: ^3.0.0
  shiki-codegen: ^3.0.0
  simple-git: ^3.27.0
  simple-git-hooks: ^2.11.1
  sirv: ^3.0.1
  splitpanes: ^3.1.8
  structured-clone-es: ^1.0.0
  taze: ^18.6.0
  theme-vitesse: ^0.8.3
  tinyglobby: ^0.2.11
  typescript: ^5.7.3
  unbuild: ^3.3.1
  unimport: ^4.1.2
  unocss: ^66.0.0
  unplugin-vue-markdown: ^28.3.0
  v-lazy-show: ^0.3.0
  vanilla-jsoneditor: ^2.4.0
  vis-data: ^7.1.9
  vis-network: ^9.1.9
  vite: ^6.1.0
  vite-hot-client: ^2.0.4
  vite-plugin-inspect: ^10.2.1
  vite-plugin-vue-inspector: ^5.3.1
  vitest: ^3.0.5
  vue: ^3.5.13
  vue-router: ^4.5.0
  vue-tsc: ^2.2.2
  vue-virtual-scroller: ^2.0.0-beta.8
  which: ^5.0.0
  ws: ^8.18.0
