packages:
  - packages/**
  - playgrounds/**
catalog:
  '@antfu/eslint-config': ^3.5.0
  '@antfu/ni': ^0.23.0
  '@antfu/utils': ^0.7.10
  '@exampledev/new.css': ^1.1.3
  '@iconify-json/bxl': ^1.2.0
  '@iconify-json/carbon': ^1.2.1
  '@iconify-json/logos': ^1.2.0
  '@iconify-json/ri': ^1.2.0
  '@iconify-json/simple-icons': ^1.2.2
  '@iconify-json/tabler': ^1.2.1
  '@nuxt/content': ^2.13.2
  '@nuxt/kit': ^3.13.1
  '@nuxt/module-builder': ^0.8.3
  '@nuxt/schema': ^3.13.1
  '@nuxt/test-utils': ^3.14.1
  '@opentelemetry/api': ^1.9.0
  '@parcel/watcher': ^2.4.1
  '@pinia/nuxt': ^0.5.4
  '@types/diff': ^5.2.2
  '@types/markdown-it': ^14.1.2
  '@types/markdown-it-link-attributes': ^3.0.5
  '@types/node': ^22.5.4
  '@types/prompts': ^2.4.9
  '@types/ua-parser-js': ^0.7.39
  '@types/which': ^3.0.4
  '@types/ws': ^8.5.12
  '@unocss/core': ^0.62.3
  '@unocss/eslint-config': ^0.62.3
  '@unocss/nuxt': ^0.62.3
  '@unocss/preset-attributify': ^0.62.3
  '@unocss/preset-icons': ^0.62.3
  '@unocss/preset-mini': ^0.62.3
  '@unocss/preset-uno': ^0.62.3
  '@unocss/reset': ^0.62.3
  '@unocss/runtime': ^0.62.3
  '@vitest/ui': ^2.0.5
  '@vue/devtools-applet': 7.4.4
  '@vue/devtools-core': 7.4.4
  '@vue/devtools-kit': 7.4.4
  '@vueuse/core': ^11.0.3
  '@vueuse/integrations': ^11.0.3
  '@vueuse/nuxt': ^11.0.3
  '@xterm/addon-fit': ^0.10.0
  '@xterm/xterm': ^5.5.0
  birpc: ^0.2.17
  bumpp: ^9.5.2
  consola: ^3.2.3
  conventional-changelog-cli: ^5.0.0
  cronstrue: ^2.50.0
  cypress: ^13.14.2
  defu: ^6.1.4
  destr: ^2.0.3
  diff: ^7.0.0
  error-stack-parser-es: ^0.1.5
  eslint: ^9.10.0
  eslint-plugin-format: ^0.1.2
  esno: ^4.7.0
  execa: ^7.2.0
  fast-npm-meta: ^0.2.2
  flatted: ^3.3.1
  floating-vue: 5.2.2
  focus-trap: ^7.5.4
  fuse.js: ^7.0.0
  get-port-please: ^3.1.2
  global-directory: ^4.0.1
  hookable: ^5.5.3
  image-meta: ^0.2.1
  is-installed-globally: ^1.0.0
  json-editor-vue: ^0.16.0
  launch-editor: ^2.9.1
  lint-staged: ^15.2.10
  local-pkg: ^0.5.0
  magicast: ^0.3.5
  markdown-it: ^14.1.0
  markdown-it-link-attributes: ^4.0.1
  nanoid: ^5.0.7
  nitropack: ^2.9.7
  nuxt: ^3.13.1
  nypm: ^0.3.11
  ofetch: ^1.3.4
  ohash: ^1.1.3
  pathe: ^1.1.2
  perfect-debounce: ^1.0.0
  pinia: ^2.2.2
  pkg-types: ^1.2.0
  prompts: ^2.4.2
  quicktype-core: ^23.0.170
  rc9: ^2.1.2
  scule: ^1.3.0
  semver: ^7.6.3
  shiki: ^1.16.3
  simple-git: ^3.26.0
  simple-git-hooks: ^2.11.1
  sirv: ^2.0.4
  splitpanes: ^3.1.5
  taze: ^0.16.7
  theme-vitesse: ^0.8.3
  tiged: ^2.12.7
  tinyglobby: ^0.2.6
  typescript: ^5.6.2
  ua-parser-js: ^1.0.38
  unbuild: ^2.0.0
  unimport: ^3.11.1
  unocss: ^0.62.3
  unplugin-vue-markdown: ^0.26.2
  v-lazy-show: ^0.2.4
  vanilla-jsoneditor: ^0.23.8
  vis-data: ^7.1.9
  vis-network: ^9.1.9
  vite-hot-client: ^0.2.3
  vite-plugin-inspect: ^0.8.7
  vite-plugin-vue-inspector: ^5.2.0
  vitest: ^2.0.5
  vue: ^3.5.4
  vue-router: ^4.4.3
  vue-tsc: ^2.1.6
  vue-virtual-scroller: 2.0.0-beta.8
  which: ^3.0.1
  ws: ^8.18.0
