packages:
  - packages/**
  - playgrounds/**

shamefullyHoist: true
ignoreWorkspaceRootCheck: true
strictPeerDependencies: false
autoInstallPeers: true
resolutionMode: highest

catalogs:
  buildtools:
    '@discoveryjs/cli': ^2.14.6
    '@discoveryjs/discovery': 1.0.0-beta.92
    '@nuxt/module-builder': ^1.0.2
    '@parcel/watcher': ^2.5.1
    '@pinia/nuxt': ^0.11.2
    '@unocss/core': ^66.5.1
    '@unocss/eslint-config': ^66.5.1
    '@unocss/nuxt': ^66.5.1
    '@unocss/preset-attributify': ^66.5.1
    '@unocss/preset-icons': ^66.5.1
    '@unocss/preset-mini': ^66.5.1
    '@unocss/preset-uno': ^66.5.1
    '@vueuse/nuxt': ^13.9.0
    esbuild: ^0.25.10
    exsolve: ^1.0.7
    lightningcss: ^1.30.1
    nitropack: ^2.12.6
    nuxt: ^3.19.2
    rollup: ^4.52.0
    shiki-codegen: ^3.13.0
    unbuild: ^3.6.1
    unocss: ^66.5.1
    unplugin-vue: ^7.0.1
    unplugin-vue-markdown: ^29.1.0
    vite: ^7.1.11
  cli:
    '@antfu/eslint-config': ^5.4.1
    '@antfu/ni': ^26.0.1
    '@nuxt/eslint': ^1.9.0
    '@nuxt/test-utils': ^3.19.2
    '@vitest/ui': ^3.2.4
    bumpp: ^10.2.3
    conventional-changelog-cli: ^5.0.0
    cypress: ^13.17.0
    eslint: ^9.36.0
    eslint-flat-config-utils: ^2.1.4
    eslint-plugin-antfu: ^3.1.1
    eslint-plugin-format: ^1.0.2
    lint-staged: ^16.1.6
    nuxt-eslint-auto-explicit-import: ^0.1.1
    simple-git-hooks: ^2.13.1
    taze: ^19.7.0
    tsx: ^4.20.5
    typescript: ^5.9.2
    vitest: ^3.2.4
    vue-tsc: ^3.0.7
  frontend:
    '@antfu/utils': ^9.2.1
    '@unocss/reset': ^66.5.1
    '@unocss/runtime': ^66.5.1
    '@vue/devtools-applet': ^7.7.7
    '@vue/devtools-core': ^7.7.7
    '@vueuse/core': ^13.9.0
    '@vueuse/integrations': ^13.9.0
    '@xterm/addon-fit': ^0.10.0
    '@xterm/xterm': ^5.5.0
    birpc: ^2.5.0
    cronstrue: ^2.61.0
    diff: ^8.0.2
    error-stack-parser-es: ^1.0.5
    floating-vue: ^5.2.2
    focus-trap: ^7.6.5
    fuse.js: ^7.1.0
    hookable: ^5.5.3
    json-editor-vue: ^0.18.1
    markdown-it: ^14.1.0
    markdown-it-link-attributes: ^4.0.1
    my-ua-parser: ^2.0.4
    ofetch: ^1.4.1
    ohash: ^2.0.11
    pathe: ^2.0.3
    perfect-debounce: ^1.0.0
    pinia: ^3.0.3
    quicktype-core: 22.0.0
    scule: ^1.3.0
    shiki: ^3.13.0
    splitpanes: ^3.2.0
    structured-clone-es: ^1.0.0
    theme-vitesse: ^1.0.0
    v-lazy-show: ^0.3.0
    vanilla-jsoneditor: ^3.9.0
    vis-data: ^8.0.3
    vis-network: ^10.0.2
    vite-hot-client: ^2.1.0
    vue: ^3.5.21
    vue-router: ^4.5.1
    vue-virtual-scroller: ^2.0.0-beta.8
  icons:
    '@iconify-json/bxl': ^1.2.2
    '@iconify-json/carbon': ^1.2.13
    '@iconify-json/logos': ^1.2.9
    '@iconify-json/ph': ^1.2.2
    '@iconify-json/ri': ^1.2.5
    '@iconify-json/simple-icons': ^1.2.52
    '@iconify-json/tabler': ^1.2.23
  playground:
    '@exampledev/new.css': ^1.1.3
  prod:
    '@nuxt/kit': ^3.19.2
    '@vue/devtools-kit': ^7.7.7
    consola: ^3.4.2
    defu: ^6.1.4
    destr: ^2.0.5
    execa: ^8.0.1
    fast-npm-meta: ^0.4.6
    get-port-please: ^3.2.0
    image-meta: ^0.2.1
    is-installed-globally: ^1.0.0
    launch-editor: ^2.11.1
    local-pkg: ^1.1.2
    magicast: ^0.3.5
    nypm: ^0.6.2
    pkg-types: ^2.3.0
    prompts: ^2.4.2
    semver: ^7.7.2
    simple-git: ^3.28.0
    sirv: ^3.0.2
    tinyglobby: ^0.2.15
    vite-plugin-inspect: ^11.3.3
    vite-plugin-vue-tracer: ^1.0.0
    which: ^5.0.0
    ws: ^8.18.3
  types:
    '@nuxt/schema': ^3.19.2
    '@types/diff': ^8.0.0
    '@types/markdown-it': ^14.1.2
    '@types/markdown-it-link-attributes': ^3.0.5
    '@types/node': ^24.5.2
    '@types/prompts': ^2.4.9
    '@types/which': ^3.0.4
    '@types/ws': ^8.18.1
    '@unhead/schema': ^2.0.17
    unimport: ^5.3.0
onlyBuiltDependencies:
  - '@parcel/watcher'
  - better-sqlite3
  - cypress
  - esbuild
  - json-editor-vue
  - simple-git-hooks
  - unrs-resolver
  - vue-demi
