packages:
  - packages/**
  - playgrounds/**
catalog:
  '@antfu/eslint-config': ^3.14.0
  '@antfu/ni': ^23.2.0
  '@antfu/utils': ^8.1.0
  '@discoveryjs/cli': ^2.12.1
  '@discoveryjs/discovery': 1.0.0-beta.92
  '@exampledev/new.css': ^1.1.3
  '@iconify-json/bxl': ^1.2.2
  '@iconify-json/carbon': ^1.2.5
  '@iconify-json/logos': ^1.2.4
  '@iconify-json/ri': ^1.2.5
  '@iconify-json/simple-icons': ^1.2.20
  '@iconify-json/tabler': ^1.2.14
  '@nuxt/content': ^2.13.4
  '@nuxt/eslint': ^0.7.5
  '@nuxt/kit': ^3.15.1
  '@nuxt/module-builder': ^0.8.3
  '@nuxt/schema': ^3.15.1
  '@nuxt/test-utils': ^3.15.4
  '@opentelemetry/api': ^1.9.0
  '@parcel/watcher': ^2.5.0
  '@pinia/nuxt': ^0.9.0
  '@shikijs/langs-precompiled': ^1.27.2
  '@types/diff': ^7.0.0
  '@types/markdown-it': ^14.1.2
  '@types/markdown-it-link-attributes': ^3.0.5
  '@types/node': ^22.10.6
  '@types/prompts': ^2.4.9
  '@types/which': ^3.0.4
  '@types/ws': ^8.5.13
  '@unocss/core': ^65.4.0
  '@unocss/eslint-config': ^65.4.0
  '@unocss/nuxt': ^65.4.0
  '@unocss/preset-attributify': ^65.4.0
  '@unocss/preset-icons': ^65.4.0
  '@unocss/preset-mini': ^65.4.0
  '@unocss/preset-uno': ^65.4.0
  '@unocss/reset': ^65.4.0
  '@unocss/runtime': ^65.4.0
  '@vitest/ui': ^2.1.8
  '@vue/devtools-applet': ^7.7.0
  '@vue/devtools-core': ^7.7.0
  '@vue/devtools-kit': ^7.7.0
  '@vueuse/core': ^12.4.0
  '@vueuse/integrations': ^12.4.0
  '@vueuse/nuxt': ^12.4.0
  '@xterm/addon-fit': ^0.10.0
  '@xterm/xterm': ^5.5.0
  birpc: ^2.0.19
  bumpp: ^9.10.1
  consola: ^3.4.0
  conventional-changelog-cli: ^5.0.0
  cronstrue: ^2.52.0
  cypress: ^13.17.0
  defu: ^6.1.4
  destr: ^2.0.3
  diff: ^7.0.0
  error-stack-parser-es: ^1.0.5
  esbuild: ^0.24.2
  eslint: ^9.18.0
  eslint-flat-config-utils: ^1.0.0
  eslint-plugin-antfu: ^2.7.0
  eslint-plugin-format: ^1.0.1
  esno: ^4.8.0
  execa: ^7.2.0
  fast-npm-meta: ^0.2.2
  flatted: ^3.3.2
  floating-vue: ^5.2.2
  focus-trap: ^7.6.4
  fuse.js: ^7.0.0
  get-port-please: ^3.1.2
  hookable: ^5.5.3
  image-meta: ^0.2.1
  is-installed-globally: ^1.0.0
  json-editor-vue: ^0.17.3
  launch-editor: ^2.9.1
  lint-staged: ^15.3.0
  local-pkg: ^1.0.0
  magicast: ^0.3.5
  markdown-it: ^14.1.0
  markdown-it-link-attributes: ^4.0.1
  my-ua-parser: ^2.0.4
  nanoid: ^5.0.9
  nitropack: ^2.10.4
  nuxt: ^3.15.1
  nuxt-eslint-auto-explicit-import: ^0.1.1
  nypm: ^0.4.1
  ofetch: ^1.4.1
  ohash: ^1.1.4
  pathe: ^2.0.1
  perfect-debounce: ^1.0.0
  pinia: ^2.3.0
  pkg-types: ^1.3.1
  prompts: ^2.4.2
  quicktype-core: ^23.0.170
  rc9: ^2.1.2
  scule: ^1.3.0
  semver: ^7.6.3
  shiki: ^1.27.2
  shiki-codegen: ^1.27.2
  simple-git: ^3.27.0
  simple-git-hooks: ^2.11.1
  sirv: ^3.0.0
  splitpanes: ^3.1.8
  taze: ^18.2.0
  theme-vitesse: ^0.8.3
  tinyglobby: ^0.2.10
  typescript: ^5.7.3
  unbuild: ^3.3.1
  unimport: ^3.14.6
  unocss: ^65.4.0
  unplugin-vue-markdown: ^28.0.0
  v-lazy-show: ^0.3.0
  vanilla-jsoneditor: ^2.3.3
  vis-data: ^7.1.9
  vis-network: ^9.1.9
  vite: ^6.0.7
  vite-hot-client: ^2.0.4
  vite-plugin-inspect: ^10.0.7
  vite-plugin-vue-inspector: ^5.3.1
  vitest: ^2.1.8
  vue: ^3.5.13
  vue-router: ^4.5.0
  vue-tsc: ^2.2.0
  vue-virtual-scroller: ^2.0.0-beta.8
  which: ^3.0.1
  ws: ^8.18.0
