// Generated by components discovery
declare module 'vue' {
  export interface GlobalComponents {
    'NButton': typeof import('../../src/components/NButton.vue')['default'],
    'NCard': typeof import('../../src/components/NCard.vue')['default'],
    'NCheckbox': typeof import('../../src/components/NCheckbox.vue')['default'],
    'NDialog': typeof import('../../src/components/NDialog.vue')['default'],
    'NDropdown': typeof import('../../src/components/NDropdown.vue')['default'],
    'NIcon': typeof import('../../src/components/NIcon.vue')['default'],
    'NLink': typeof import('../../src/components/NLink.vue')['default'],
    'NRadio': typeof import('../../src/components/NRadio.vue')['default'],
    'NSwitch': typeof import('../../src/components/NSwitch.vue')['default'],
    'NTextInput': typeof import('../../src/components/NTextInput.vue')['default'],
    'NTip': typeof import('../../src/components/NTip.vue')['default'],
    'NuxtExampleLayout': typeof import('../../src/components/NuxtExampleLayout.vue')['default'],
    'UnoIcon': typeof import('../../../../node_modules/@unocss/nuxt/runtime/UnoIcon.vue')['default'],
    'NuxtWelcome': typeof import('../../../../node_modules/nuxt3/dist/app/components/nuxt-welcome.vue')['default'],
    'ClientOnly': typeof import('../../../../node_modules/nuxt3/dist/app/components/client-only')['default']
  }
}
export {}
