// Generated by nuxi
/// <reference path="nitro.d.ts" />
/// <reference types="nuxt3" />
/// <reference path="plugins.d.ts" />
/// <reference path="auto-imports.d.ts" />
/// <reference path="imports.d.ts" />

export {}
