onlyBuiltDependencies:
  - better-sqlite3
  - esbuild
  - sharp
  - vue-demi
packages: []
catalog:
  '@iconify-json/heroicons': ^1.2.2
  '@iconify-json/ph': ^1.2.2
  '@iconify-json/simple-icons': ^1.2.27
  '@nuxt/content': ^2.13.4
  '@nuxt/devtools': ^2.1.3
  '@nuxt/fonts': ^0.10.3
  '@nuxt/image': ^1.9.0
  '@nuxt/ui-pro': ^1.7.0
  '@nuxthq/studio': ^2.2.1
  '@nuxtjs/plausible': ^1.2.0
  '@vueuse/core': ^12.7.0
  '@vueuse/nuxt': ^12.7.0
  better-sqlite3: ^11.8.1
  nuxt: ^3.15.4
  nuxt-og-image: ^4.1.5
