onlyBuiltDependencies:
  - better-sqlite3
  - esbuild
  - sharp
  - vue-demi
packages: []
catalog:
  '@iconify-json/heroicons': ^1.2.2
  '@iconify-json/ph': ^1.2.2
  '@iconify-json/simple-icons': ^1.2.27
  '@nuxt/content': ^3.7.1
  '@nuxt/devtools': ^2.1.3
  '@nuxt/fonts': ^0.0.0
  '@nuxt/image': ^0.0.0
  '@nuxt/ui': ^4.0.1
  '@nuxthq/studio': ^2.2.1
  '@nuxtjs/plausible': ^1.2.0
  '@vueuse/core': ^12.7.0
  '@vueuse/nuxt': ^12.7.0
  better-sqlite3: ^11.8.1
  docus: ^5.2.1
  nuxt: ^4.1.3
  tailwindcss: ^4.1.14
