name: autofix.ci # needed to securely identify the workflow

on:
  pull_request:
    paths-ignore:
      - 'docs/**'

jobs:
  ci:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: pnpm
      - run: pnpm install
      - run: pnpm lint --fix
      - uses: autofix-ci/action@2891949f3779a1cafafae1523058501de3d4e944
      - run: pnpm build
      - run: pnpm typecheck
